language: php
php:
  - '7.0.0'
script:
  - composer install --ignore-platform-reqs
  - zip -r vips-image-editor.zip . -x \*.git\*
deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file: "vips-image-editor.zip"
  skip_cleanup: true
  on:
    tags: true
